version: "3"

services:
  qg_app_backend:
    container_name: qg_app_backend
    build:
      context: Docker/qg_app_backend
      dockerfile: Docker/qg_app_backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    networks:
      - qg_app
    volumes:
      - ./qg_app_backend:/qg_app_backend
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  qg_app_frontend:
    container_name: qg_app_frontend
    build:
      context: Docker/qg_app_frontend
      dockerfile: Docker/qg_app_frontend/Dockerfile
    command: yarn dev
    depends_on:
      - qg_app_backend
    networks:
      - qg_app
    volumes:
      - ./qg_app_frontend:/qg_app_frontend
      - ./qg_app_frontend/node_modules:/qg_app_frontend/node_modules
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

networks:
  qg_app:
    external: false