version: "3"

services:
  qg_app_backend:
    container_name: qg_app_backend
    build:
      context: ./
      dockerfile: Docker/qg_app_backend/Dockerfile
    command: mvn spring-boot:run
    ports:
      - "9000:9000"
    networks:
      - qg_app
    volumes:
      - ./qg_app_backend:/qg_app_backend
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  qg_app_frontend:
    container_name: qg_app_frontend
    build:
      dockerfile: Docker/qg_app_frontend/Dockerfile
      context: ./
    command: yarn dev
    depends_on:
      - qg_app_backend
    networks:
      - qg_app
    volumes:
      - ./qg_app_frontend:/qg_app_frontend
      - /qg_app_frontend/node_modules
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

networks:
  qg_app:
    external: true